spring:
  application:
    name: booking-service

server:
  port: 8090


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



