spring:
  application:
    name: gateway-service

server:
  port: 8765


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



